version: 2.1

orbs:
  unity: game-ci/unity@x.y

workflows:
  build-unity-project:
    jobs:
      # Windows
      - unity/test:
          name: 'test-windows'
          step-name: 'Check if the tests run and results are uploaded'
          unity-license-var-name: 'UNITY_ENCODED_LICENSE'
          unity-username-var-name: 'UNITY_USERNAME'
          unity-password-var-name: 'UNITY_PASSWORD'
          executor:
            name: 'unity/windows-2022'
            size: 'large'
            editor_version: '2021.3.37f1'
            target_platform: 'windows-il2cpp'
          project-path: 'D:\UnityPractice\UnityTestingCICD'
          test-platform: 'playmode'
          context: unity

      # macOS
      - unity/test:
          name: 'test-osx'
          step-name: 'Check if the tests run and results are uploaded'
          unity-license-var-name: 'UNITY_ENCODED_LICENSE'
          unity-username-var-name: 'UNITY_USERNAME'
          unity-password-var-name: 'UNITY_PASSWORD'
          executor:
            name: 'unity/macos'
            editor_version: '2021.3.37f1'
            resource_class: 'large'
          project-path: 'D:\UnityPractice\UnityTestingCICD'
          test-platform: 'playmode'
          context: unity